server:
  port: 10000

spring:
  application:
    name: minitao-gateway
  redis:
    host: localhost
    password: ****
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: item
          uri: lb://minitao-item
          predicates:
          - Path=/item/**
          filters:
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@hostKeyResolver}'
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 3
        - id: cart
          uri: lb://minitao-cart
          predicates:
          - Path=/cart/**

        - id: user
          uri: lb://minitao-user
          predicates:
          - Path=/user/**
          filters:
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@hostKeyResolver}'
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 3
        - id: order
          uri: lb://minitao-order
          predicates:
          - Path=/order/**


jwt:
  tokenHead: taoToken
  secret: chqmyg
  expiration: 3600000
