server:
  port: 10000

spring:
  application:
    name: minitao-gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.235.23:3306/minitao?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1020
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

  redis:
    host: 39.97.235.23
    port: 6379
    password: 654321
    database: 3
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: item
          uri: lb://minitao-item
          predicates:
            - Path=/item/**
          filters:
          - RewritePath=/item/(?<segment>.*), /$\{segment}

        - id: cart
          uri: lb://minitao-cart
          predicates:
          - Path=/cart/**
          filters:
          - RewritePath=/cart/(?<segment>.*), /$\{segment}

        - id: user
          uri: lb://minitao-user
          predicates:
          - Path=/user/**
          filters:
          - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: store
          uri: lb://minitao-store
          predicates:
          - Path=/store/**
          filters:
          - RewritePath=/user/(?<segment>.*), /$\{segment}

minitao:
  filter:
    allowPath:
      - /item
      - /user
      - /auth


jwt:
  tokenHead: taoToken
  secret: chqmyg
  expiration: 3600000