server:
  port: 10000

spring:
  application:
    name: minitao-gateway
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://120.79.220.182:3306/minitao?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: abc987
#    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: ****
    port: ****
    password: ****
    database: ****
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: item
          uri: lb://minitao-item
          predicates:
            - Path=/item/**
          filters:
          - RewritePath=/item/(?<segment>.*), /$\{segment}

        - id: cart
          uri: lb://minitao-cart
          predicates:
          - Path=/cart/**
          filters:
          - RewritePath=/cart/(?<segment>.*), /$\{segment}

        - id: user
          uri: lb://minitao-user
          predicates:
          - Path=/user/**
          filters:
          - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: auth
          uri: lb://minitao-auth
          predicates:
          - Path=/oauth/**
          filters:
          - RewritePath=/oauth/(?<segment>.*), /$\{segment}

        - id: order
          uri: lb://minitao-order
          predicates:
          - Path=/order/**
          filters:
          - RewritePath=/user/(?<segment>.*), /$\{segment}

minitao:
  filter:
    allowPath:
      - /item
      - /user
      - /oauth


jwt:
  tokenHead: taoToken
  secret: chqmyg
  expiration: 3600000