server:
  port: 9004

spring:
  application:
    name: minitao-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.235.23:3306/minitao?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1020
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 39.97.235.23
    database: 2
    password: 654321

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.minitao.user.entity
  configuration:
    map-underscore-to-camel-case: true


jwt:
  tokenHead: taoToken
  secret: chqmyg
  expiration: 3600000
taoEncrypt:
  key: 12345678
