server:
  port: 9004

spring:
  application:
    name: minitao-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.220.182:3306/miniTao_user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc987
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 120.79.220.182
    port: 6379
    database: 2
    password: abc987

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.minitao.user.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  tokenHead: taoToken
  secret: chqmyg
  expiration: 3600000
taoEncrypt:
  key: 12345678

minitao:
  filter:
    allowPath:
      - /user/login
      - /user/register
      - /user/code
      - /user/verifyCode


aliyun:
  endPoint: dysmsapi.aliyuncs.com
  accessKeyId: LTAI4FpsHDjNU41Lnfopkobj
  accessKeySecret: wRciv2ycIUFg1wJcmviM3dh5qErgEd