server:
  port: 9002
spring:
  application:
    name: minitao-item
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniTao_store?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ****
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: ****
    port: 6379
    database: 2
    password: 
  kafka:
    # Kafka服务地址
    bootstrap-servers: 120.79.220.182:9092
    consumer:
      # 指定一个默认的组名
      group-id: consumer-group1
      #序列化反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      # 批量抓取
      batch-size: 65536
      # 缓存容量
      buffer-memory: 524288
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: tx_minitao

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.item.component.entity

minitao:
  filter:
    allowPath:
    - /item/seckill
    - /item/putSeckillStore


aliyun:
  endPoint: oss-cn-guangzhou.aliyuncs.com
  urlPrefix: http://oss-cn-guangzhou.aliyuncs.com
  accessKeyId: 
  accessKeySecret: 
  bucketName: 
