server:
  port:
    9000
spring:
  application:
    name: minitao-auth
  redis:
    host: ****
    password: ****
    database: 2


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
