server:
  port: 9005

spring:
  application:
    name: minitao-cart
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniTao_user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ****
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
