server:
  port: 9006

spring:
  application:
    name: minitao-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.220.182:3306/miniTao_user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc987
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        #与config对应
        tx-service-group: tx_minitao

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.minitao.order.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

