server:
  port: 9001
spring:
  application:
    name: minitao-item

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
   # mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.minitao.item.entity



